spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/persistdb
  jpa:
    hibernate:
    # will read data from disk if present
      ddl-auto: update
    show-sql: false

---
spring:
  profiles: test
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:./database/testdb
  jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true